name: docs-build


permissions:
  id-token: write 
  contents: read  

on:
  workflow_dispatch:



jobs:
  build:
    runs-on: eks-runner
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: set image tag env
        run: echo "IMAGE_TAG=$(echo moonsama/docs:ui-production-$(git rev-parse --short HEAD)-$(date +%F-%H-%M))" >> $GITHUB_ENV  
        working-directory: remote

      # Docker build image part start
      - name: Build Image
        run: |
          docker build \
          -t ${{ env.IMAGE_TAG }} .
        working-directory: remote

      - name: Push Image
        run: docker push ${{ env.IMAGE_TAG }}
